{
  "formatVersion": "1.1",
  "component": {
    "group": "org.purejava",
    "module": "flatpak-update-portal",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.1"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-core",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-transport-native-unixsocket",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "flatpak-update-portal-1.0.0.jar",
          "url": "flatpak-update-portal-1.0.0.jar",
          "size": 19800,
          "sha512": "b999849b15fb83826e700d97793bc393031541805730dff8c97ce7afc39f7ce9ec5a6b59ab4625cd7b6759cf4e1184c64a4221bc5d39a6cbf4e0668cf0c4010d",
          "sha256": "7af9e20f83e218eb47f931242dd7192361f8c013734aa38d0baed9a8ff5b38da",
          "sha1": "473cf56b37866e69b8d7059117e698e3c6133d0f",
          "md5": "83da3f98caa09d1061c36a7668131add"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.1"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-core",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-transport-native-unixsocket",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "flatpak-update-portal-1.0.0.jar",
          "url": "flatpak-update-portal-1.0.0.jar",
          "size": 19800,
          "sha512": "b999849b15fb83826e700d97793bc393031541805730dff8c97ce7afc39f7ce9ec5a6b59ab4625cd7b6759cf4e1184c64a4221bc5d39a6cbf4e0668cf0c4010d",
          "sha256": "7af9e20f83e218eb47f931242dd7192361f8c013734aa38d0baed9a8ff5b38da",
          "sha1": "473cf56b37866e69b8d7059117e698e3c6133d0f",
          "md5": "83da3f98caa09d1061c36a7668131add"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flatpak-update-portal-1.0.0-sources.jar",
          "url": "flatpak-update-portal-1.0.0-sources.jar",
          "size": 10326,
          "sha512": "01eaef9d0da92b95872dee05f125538166557a2635f2098be5fc91e6efd69e09df4ee5877a8c13deaa2bfc91e7bc28c53c714a7a06439cde8c99105329adbfd6",
          "sha256": "e45d26c7421fcf7fb55c0e5b4720c28f244667f04f92d9fbdc61b91844272d87",
          "sha1": "d9bc1e75f73c1eb7eac90861a95c9f23a404942d",
          "md5": "7497e450b37e7046e08e28a7d71d2be8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flatpak-update-portal-1.0.0-javadoc.jar",
          "url": "flatpak-update-portal-1.0.0-javadoc.jar",
          "size": 4191512,
          "sha512": "bc1acaaa300d8815354379e15eecd241b08215582230de24916872bd6fb0bc975e634f578792c8fac98948ac5f20164b3252bd05fa4ee522e2224048e3b0ee9e",
          "sha256": "2cd8913bff66d05f219d57d222e266afa069aba9b2632f878cc0f02eb1bc2ed6",
          "sha1": "6405808b0936ae01183e436d6fbd629655359c0a",
          "md5": "f22b603518a2fa112c89a3619e861493"
        }
      ]
    }
  ]
}
