{
  "formatVersion": "1.1",
  "component": {
    "group": "org.purejava",
    "module": "flatpak-update-portal",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.1"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-core",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-transport-native-unixsocket",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "flatpak-update-portal-1.0-SNAPSHOT.jar",
          "url": "flatpak-update-portal-1.0-SNAPSHOT.jar",
          "size": 19800,
          "sha512": "196d8abfa0d15a62b59ca42998a1ec476e9fd20d3898c66665889177c9de4fc3eb43fc1046ad9fc859d7a582bc9686ab5196b3e837013c3921fea7d46de41861",
          "sha256": "e84883e4712a7643e36e7cf37915660e8437aeacd4919fc2976eeb583aab240f",
          "sha1": "3598676725286b72d3823600d4e9950b810cc177",
          "md5": "47287e36133ac0630eabd093cc268e18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.1"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-core",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-transport-native-unixsocket",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "flatpak-update-portal-1.0-SNAPSHOT.jar",
          "url": "flatpak-update-portal-1.0-SNAPSHOT.jar",
          "size": 19800,
          "sha512": "196d8abfa0d15a62b59ca42998a1ec476e9fd20d3898c66665889177c9de4fc3eb43fc1046ad9fc859d7a582bc9686ab5196b3e837013c3921fea7d46de41861",
          "sha256": "e84883e4712a7643e36e7cf37915660e8437aeacd4919fc2976eeb583aab240f",
          "sha1": "3598676725286b72d3823600d4e9950b810cc177",
          "md5": "47287e36133ac0630eabd093cc268e18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flatpak-update-portal-1.0-SNAPSHOT-sources.jar",
          "url": "flatpak-update-portal-1.0-SNAPSHOT-sources.jar",
          "size": 10326,
          "sha512": "d3884be647b81aee46bff9751ac7872c581fec3c82d61c3a7311b67aceca22de63c71e5a7a027fd297ac7cb51e30e2d21c3e70a9399553dec0b93aec279582b9",
          "sha256": "664dd077cc9f5951c613d4dda3046817c011dd1f4cfc887762d755244903d493",
          "sha1": "7fc81ec2935c17f6995d6ab006295880691e3616",
          "md5": "d10d817cae0dbb268c062859d12ea6a9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flatpak-update-portal-1.0-SNAPSHOT-javadoc.jar",
          "url": "flatpak-update-portal-1.0-SNAPSHOT-javadoc.jar",
          "size": 4191682,
          "sha512": "03829b0d9f415a22c49200634eef18c51797a05567e7eea81961e7886fcf9f5c8faa67dff0bee1f6e1b5c80457057cd39f4db75b9068373d172c4b43705c59eb",
          "sha256": "f66799a88f759e5fbbb505ba7a011a2743f8de1476f8076ff4e876c9e2892c63",
          "sha1": "0fcb69b2c87c229fde6feba2230d9489cfa1a356",
          "md5": "ce7a0991f5f16807e406631a1f78227e"
        }
      ]
    }
  ]
}
