{
  "formatVersion": "1.1",
  "component": {
    "group": "org.purejava",
    "module": "flatpak-update-portal",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.1"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-core",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-transport-native-unixsocket",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "flatpak-update-portal-1.0-SNAPSHOT.jar",
          "url": "flatpak-update-portal-1.0-SNAPSHOT.jar",
          "size": 18718,
          "sha512": "5a39067a9bab2fd1cf74e6427f80514bc94dc7bb86b8d8a9c35051d6b2ef220f5774827cb96eaed4410c4508ea9a02b376b7b627f789fd9f673a694c4da232ff",
          "sha256": "4204f87076d513bc68e3ad8f326e6d399ed09c863b5f31ae606b297161737fbc",
          "sha1": "58feb720c3d55ad6e8ac88eee87ba1ef880cb72e",
          "md5": "896c0019efdc5897716dc66cbaac53a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.1"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-core",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "com.github.hypfvieh",
          "module": "dbus-java-transport-native-unixsocket",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "flatpak-update-portal-1.0-SNAPSHOT.jar",
          "url": "flatpak-update-portal-1.0-SNAPSHOT.jar",
          "size": 18718,
          "sha512": "5a39067a9bab2fd1cf74e6427f80514bc94dc7bb86b8d8a9c35051d6b2ef220f5774827cb96eaed4410c4508ea9a02b376b7b627f789fd9f673a694c4da232ff",
          "sha256": "4204f87076d513bc68e3ad8f326e6d399ed09c863b5f31ae606b297161737fbc",
          "sha1": "58feb720c3d55ad6e8ac88eee87ba1ef880cb72e",
          "md5": "896c0019efdc5897716dc66cbaac53a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flatpak-update-portal-1.0-SNAPSHOT-sources.jar",
          "url": "flatpak-update-portal-1.0-SNAPSHOT-sources.jar",
          "size": 9755,
          "sha512": "6bd3134ccb01045efe68fc46aedf1b18240ad13fa99b8541efe78b892617fbaaeff828cb177bfd192c397548b56e8f1eced2c57bc6d0f104715dc811e435ec0b",
          "sha256": "80f01440bf7c311b465cb51aef9bc6897b84ddde7f3090d4aea88908307d237e",
          "sha1": "c1030eb73644c70d14dfc4ee3315149e662844e6",
          "md5": "9c3d4768ea683aafcd526ce8e428fd52"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flatpak-update-portal-1.0-SNAPSHOT-javadoc.jar",
          "url": "flatpak-update-portal-1.0-SNAPSHOT-javadoc.jar",
          "size": 4190727,
          "sha512": "8e7aa7a145c358674c240f87f910efcdbf665478eaaf57066cb1f6155f601f2765056e844d3a08fd4aba23029ea0d53d2546b4b50349f551c906aa4152362588",
          "sha256": "e25e3ae778f7f433b316cb4a7d7fc1f390273e1deb56b35d5a9b17e5ceab2064",
          "sha1": "d95fd969e4420aef2708c1b9b102b21091bb9a2f",
          "md5": "8ca4d3264c2e7c4d6852ddaebc0c812a"
        }
      ]
    }
  ]
}
